import numpy as np
A=np.arange(15)
print(A)
B=np.sqrt(A)
print(B)
C=np.exp(A)
print(C)
D=np.add(A,B)
print(D)
E=np.maximum(A,B)
print(E)
F=np.array([1,0,5,2,3,4,5,6,7,8,9,10,11,12,13])
G=np.maximum(A,F)
print(G)
